export * from './index-minimal';
import createAdaptiveCardsAttachmentMiddleware from './adaptiveCards/createAdaptiveCardsAttachmentMiddleware';
import createCognitiveServicesSpeechServicesPonyfillFactory from './createCognitiveServicesSpeechServicesPonyfillFactory';
import createStyleSet from './createFullStyleSet';
import createDirectLineSpeechAdapters from './createDirectLineSpeechAdapters';
import ReactWebChat from './FullReactWebChat';
import renderMarkdown from './renderMarkdown';
declare const renderWebChat: any;
export declare const createDirectLine: (options: any) => any;
declare const patchedHooks: any;
declare const Components: {
    Composer: any;
    Localize: any;
    AudioContent: any;
    FileContent: any;
    HTMLVideoContent: any;
    ImageContent: any;
    TextContent: any;
    VideoContent: any;
    VimeoContent: any;
    YouTubeContent: any;
    Avatar: any;
    Bubble: any;
    CarouselLayout: any;
    ErrorBox: any;
    SendStatus: any;
    SpeakActivity: any;
    StackedLayout: any;
    Timestamp: any;
    connectSendStatus: any;
    connectSpeakActivity: any;
    connectStackedLayout: any;
    DictationInterims: any;
    MicrophoneButton: any;
    SendButton: any;
    SendTextBox: any;
    SuggestedActions: any;
    UploadButton: any;
    connectDictationInterims: any;
    connectMicrophoneButton: any;
    connectSendButton: any;
    connectSendTextBox: any;
    connectSuggestedActions: any;
    connectUploadButton: any;
};
export default ReactWebChat;
export { Components, createAdaptiveCardsAttachmentMiddleware, createCognitiveServicesSpeechServicesPonyfillFactory, createDirectLineSpeechAdapters, createStyleSet, patchedHooks as hooks, renderMarkdown, renderWebChat };
